### ISSUE TITLE
Subtle: Identical rule names (ignoring capitalization)

### ISSUE THREAD

**Issue by wxsBSD** [fireeye/red_team_tool_countermeasures#13]
I noticed you have two rules named identically if you ignore capitalization. While these are valid, unique identifiers according to YARA it's not good form to do this, IMO. If anything is consuming matches from these rules and is case insensitive it will consider the two rules to be identical, which they are obviously not.

The two rules are:

Loader_MSIL_RURALBISHOP_1
Loader_MSIL_RuralBishop_1

Given that this is a subtle thing and can lead to unintended consequences downstream from these rules I suggest renaming one of the rules. I'd do it myself but I see these rules exist in a couple of places (including one in a directory called "prod") and I'm not sure exactly how this might affect anything currently using these rules so I'm just bringing this up in an issue.

**Comment by williballenthin** [comment]
Thanks for pointing this out @wxsBSD. You're definitely right. I will rename these rules to avoid causing confusion, probably by bumping the suffix number to `_2`.

**Comment by williballenthin** [comment]
renamed the TypeLibGUID rule (`production/yara/Loader_MSIL_RuralBishop_1.yar`) to `Loader_MSIL_RuralBishop_3`
