### ISSUE TITLE
Conflict in conditions - Wdscore.dll Hijack (Methodology)

### ISSUE THREAD

**Issue by don-boss670** [fireeye/red_team_tool_countermeasures#21]
In this rule "Wdscore.dll Hijack (Methodology)", we have observed that this rule is for the filename Wdscore.dll from filepath "windows\system32\oobe". But again we have the condition for the same file not from the same path in that same rule. Please clarify on this issue.

Rule:

<IndicatorItem id="3fd73d85-3042-4ea2-81c3-28f55783aab6" condition="is" preserve-case="false" negate="false">
          <Context document="imageLoadEvent" search="imageLoadEvent/filePath" type="event" />
          <Content type="string">windows\system32\oobe</Content>
        </IndicatorItem>

 <IndicatorItem id="e2032b03-22ed-47cc-94b4-64ae8efe592c" condition="is" preserve-case="false" negate="true">
          <Context document="imageLoadEvent" search="imageLoadEvent/filePath" type="event" />
          <Content type="string">windows\system32\oobe</Content>
        </IndicatorItem>

**Comment by don-boss670** [comment]
Can anyone give support to resolve above issue..........

**Comment by williballenthin** [comment]
Correct. This rule is intended to `identif[y] possible DLL search order hijacking of Wdscore.dll based on image loads from unexpected locations.` It contains a few hardcoded paths at which a malicious DLL has been observed (`windows\system32\oobe`) as well as a general methodological term looking for the DLL outside of a whitelist of expected paths (`windows\system32`).
