### ISSUE TITLE
Documentation for yara rules

### ISSUE THREAD

**Issue by K-Yo** [fireeye/red_team_tool_countermeasures#4]
Yara’s [metadata fields](https://yara.readthedocs.io/en/stable/writingrules.html#metadata) are not normalized.

Is it possible to document how they are used here?

Examples (two first rules of [all-yara.yar](https://github.com/fireeye/red_team_tool_countermeasures/blob/master/all-yara.yar))
```yara
rule HackTool_MSIL_Rubeus_1
{
    meta:
        description = "The TypeLibGUID present in a .NET binary maps directly to the ProjectGuid found in the '.csproj' file of a .NET project. This rule looks for .NET PE files that contain the ProjectGuid found in the public Rubeus project."
        md5 = "66e0681a500c726ed52e5ea9423d2654"
        rev = 4
        author = "FireEye"
    strings:
        $typelibguid = "658C8B7F-3664-4A95-9572-A3E5871DFC06" ascii nocase wide
    condition:
        uint16(0) == 0x5A4D and $typelibguid
}
rule Trojan_Raw_Generic_4
{
    meta:
        date_created = "2020-12-02"
        date_modified = "2020-12-02"
        md5 = "f41074be5b423afb02a74bc74222e35d"
        rev = 1
        author = "FireEye"
    strings:
        $s0 = { 83 ?? 02 [1-16] 40 [1-16] F3 A4 [1-16] 40 [1-16] E8 [4-32] FF ( D? | 5? | 1? ) }
        $s1 = { 0F B? [1-16] 4D 5A [1-32] 3C [16-64] 50 45 [8-32] C3 }
    condition:
        uint16(0) != 0x5A4D and all of them
}
```

**Comment by williballenthin** [comment]
The only field you should rely upon is the `description` field (and `author` but that always "FireEye"). The remainder are primarily used for correlating with some of our internal resources, so we can do things like push updates in the right order. I understand that the `md5` field looks pretty juicy; however, as described in #3, they often correspond to custom internal builds of the red team tools, and therefore are unlikely to be of much use.

Really, we should probably strip all these other fields out, and we may do that in a future release, so I'd discourage you from attaching any meaning to these other metadata fields.
