### ISSUE TITLE
SUSPICIOUS DLL LOAD (METHODOLOGY).ioc is broken (missing end tags)

### ISSUE THREAD

**Issue by pelamatt** [fireeye/red_team_tool_countermeasures#6]
rule is currently terminating at 'sear' and the following is needed to complete the file:

![Screenshot 2020-12-09 104406](https://user-images.githubusercontent.com/13698174/101651860-8a0b9c00-3a0b-11eb-9cba-9905afa79c0e.png)

```
ch="processEvent/processCmdLine" type="event" />
              <Content type="string">-userconfig</Content>
            </IndicatorItem>
          </Indicator>
        </Indicator>
      </Indicator>
  </criteria>
</OpenIOC>
```

**Comment by williballenthin** [comment]
Thanks for reporting this @pelamatt! Turns out that during our release process, an intermediate system truncated this large rule. I've updated the rule with its complete content.
