### ISSUE TITLE
"Tweak Two Rules

### ISSUE THREAD

**Issue by r1ckyb0nd** [fireeye/red_team_tool_countermeasures#8]
in "all-yara.yar: tweak two rules" what are the two rules that need to be tweaked?

Thank you,

**Comment by williballenthin** [comment]
please use git history to review the changes made to this repo. https://github.com/fireeye/red_team_tool_countermeasures/commit/ac479ae150e1541445023952f569b7ca0d190b7b

that commit removed two rules from `all-yara.yar` (but not the individual rule directories) to account for rules that are prone to match fairly widely. for those who plug in `all-yara.yar` into their detection suite without further inspection, we wanted to avoid erroneous attribution.
